### ISSUE TITLE
Error when cmorizing orog

### ISSUE THREAD

**Issue by aearamos** [EC-Earth/ece2cmor3#230]
In my Data Request for DCPP, I have the "orog" variable (129.128) in the Emon table. I'm trying to cmorize it but I get the following error:

`ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 129.128, level type 1, level 0. Dismissing task orog in table Emon`

By digging a little deeper, I found that I had a mismatch in my match_keys and varsfreq between my source.grid_. For variable 129 I had a key of (129, 128, 1, 0, 1) (variable, table, levtype, level, source.grid_), but in my varsfreq list I had 129 in different vertical levels and in a different source.grid_ (point), as in (129, 128, 1, 0, 0). 

Is there a way to change the source.grid_ without modifying the code too much? I don't want to "force" the code and drift away from the original version of ece2cmor3.
I also have 129.128 as "zg" and "zg500" in the Amon and AERday tables, respectively. Could that be a problem?

If needed I can uplolad my ppt files in here. 

Thank you.

**Comment by goord** [comment]
Hi Arthur, the problem is that zg can be either on the gridpoint or spectral grid, and ece2cmor3 doesn't handle this very well (ps 134 has the same issue). I will try to fix your problem this evening, I will try to make eec2cmor3 accept 129 (at surface level) and 134 in either GG or SH file.

**Comment by aearamos** [comment]
Hi @goord. Thank you for looking into it. 

Another matter we had was with 168.128 (tdps). Whenever I ran the cmorization, it failed for "huss" (which depends on 168 and 134). I then saw that I had two keys for tdps: (168, 128, 1, 0, 0) and (168, 128, 105, 2, 0). In my varsfreq list, however, I had only one key: (168, 128, 1, 0, 0), so I had a mismatch and the same error:

`ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 168.128, level type 105, level 2. Dismissing task huss in table Amon` 

I could fix the variable tdps by "forcing" the leveltype to be 1 in "grib_filter/get_levels", but I'm not sure that's the right fix and why I have two 168.129 in my keys. I'm assuming I should only have one before I start processing "huss" by using the ifspar.json file.

**Comment by goord** [comment]
Hi I have created a new branch orog_fix, can you test your cmorization with that one?

**Comment by aearamos** [comment]
@goord, before being able to test the fix on orog, I got this error with the dates on the ifs files:

`WARNING:ece2cmor3.ifs2cmor:Expected a single grid point and spectral file in /gpfs/scratch/pr1eel00/pr1eel17/a1bz/19900101/fc0/runtime/output/ifs/001, found ['/gpfs/scratch/pr1eel00/pr1eel17/a1bz/19900101/fc0/runtime/output/ifs/001/ICMGGa1bz+000000', '/gpfs/scratch/pr1eel00/pr1eel17/a1bz/19900101/fc0/runtime/output/ifs/001/ICMGGa1bz+199001'] and ['/gpfs/scratch/pr1eel00/pr1eel17/a1bz/19900101/fc0/runtime/output/ifs/001/ICMSHa1bz+199001', '/gpfs/scratch/pr1eel00/pr1eel17/a1bz/19900101/fc0/runtime/output/ifs/001/ICMSHa1bz+000000'];                      will take first file of each list.
INFO:ece2cmor3.grib_filter:Searching for previous month file of /gpfs/scratch/pr1eel00/pr1eel17/a1bz/19900101/fc0/runtime/output/ifs/001/ICMGGa1bz+000000
Traceback (most recent call last):
  File "./ece2cmor.py", line 114, in <module>
    main()
  File "./ece2cmor.py", line 102, in main
    maxsizegb=args.tmpsize)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 159, in perform_ifs_tasks
    outputfreq=ofreq, tempdir=tempdir, maxsizegb=maxsizegb, autofilter=auto_filter)):
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 101, in initialize
    grib_filter.initialize(ifs_gridpoint_file_, ifs_spectral_file_, temp_dir_)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/grib_filter.py", line 48, in initialize
    prev_gridpoint_file, prev_spectral_file = get_prev_files(gridpoint_file)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/grib_filter.py", line 144, in get_prev_files
    date = cmor_utils.get_ifs_date(gpfile)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/cmor_utils.py", line 124, in get_ifs_date
    return datetime.datetime.strptime(ss, "%Y%m").date()
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/_strptime.py", line 332, in _strptime
    (data_string, format))
ValueError: time data '000000' does not match format '%Y%m'
`
I think it's related to the strptime function.

**Comment by goord** [comment]
Hi Arthur, can you try to cmorize the second (or higher) leg? I think the error above is a different bug

**Comment by aearamos** [comment]
Hi Gijs,

I tried running the cmorization from the second month, based on the first, but got the same error with the date. Then I "forced" the get_prev_file to look for my ICMGGa1bz+199001 gpfile and got the following error:

`INFO:ece2cmor3.grib_filter:No regular previous month files found, taking initial state files...
Traceback (most recent call last):
  File "./ece2cmor.py", line 114, in <module>
    main()
  File "./ece2cmor.py", line 102, in main
    maxsizegb=args.tmpsize)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 159, in perform_ifs_tasks
    outputfreq=ofreq, tempdir=tempdir, maxsizegb=maxsizegb, autofilter=auto_filter)):
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 101, in initialize
    grib_filter.initialize(ifs_gridpoint_file_, ifs_spectral_file_, temp_dir_)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/grib_filter.py", line 50, in initialize
    varsfreq.update(inspect_day(grib_file.create_grib_file(gpf), grid=cmor_source.ifs_grid.point))
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/grib_filter.py", line 104, in inspect_day
    if any(frqs != frq):
TypeError: 'bool' object is not iterable`

I'm not sure why ece2cmor3 is still looking for file 000000 and not 199001.

**Comment by goord** [comment]
Hi Arthur, I tried to fix your problem in rev. 8058f414e79573f5cb08c84690e9a02c9e0abf06 in the orog-fix branch. Can you check once more if your initial state file troubles are gone now?

**Comment by aearamos** [comment]
Hi Gijs, the initial state files troubles are gone now, but I got some other errors:
First, it successfully finds orog, as in:

`INFO:ece2cmor3.postproc:Post-processing target orog in table Emon from file /gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1bz-ifs-199001/129.128.1.6 with cdo command -sp2gpl -monmean -selcode,129
`
And then, I get the following error after it cmorizes a few variables:

`INFO:ece2cmor3.ifs2cmor:Loading CMOR table Amon...
/apps/PYTHON/2.7.14/INTEL/lib/python2.7/site-packages/CMOR-3.3.3-py2.7-linux-x86_64.egg/cmor/pywrapper.py:754: UserWarning: Error: your data shape ((88838, 1)) does not match the expected variable shape ([256, 512, 0])
Check your variable dimensions before caling cmor_write
  warnings.warn(msg)
INFO:ece2cmor3.ifs2cmor:Cmorizing source variable 228 to target variable pr...
INFO:ece2cmor3.ifs2cmor:Loading CMOR table Amon...
WARNING:ece2cmor3.ifs2cmor:Skipped removal of nonempty work directory /gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1bz-ifs-199001
Traceback (most recent call last):
  File "./ece2cmor.py", line 114, in <module>
    main()
  File "./ece2cmor.py", line 102, in main
    maxsizegb=args.tmpsize)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/ece2cmorlib.py", line 163, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, cleanup=cleanup, autofilter=auto_filter, nthreads=taskthreads)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 136, in execute
    cmorize([t for t in processed_tasks if t in supported_tasks], nthreads=nthreads)
  File "/gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/ifs2cmor.py", line 335, in cmorize
    pool.map(cmor_worker, [task for task in tasks if task.status not in skip_status])
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/apps/PYTHON/2.7.14/INTEL/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IndexError: list index out of range`

And then I have some errors in cmor.load_table due to the index. 

[nohup.txt](https://github.com/EC-Earth/ece2cmor3/files/2356589/nohup.txt)

Attached is my output.

**Comment by goord** [comment]
Strange, it says your orography doesn't fit onto your grid... Can you check the file /gpfs/scratch/pr1eel00/pr1eel17/a1bz/auto-ecearth3/ece2cmor/ece2cmor3/atm-fc0-199001/a1bz-ifs-199001/129.128.1.6 and apply the CDO command ```cdo -f nc -sp2gpl -monmean -selcode,129``` to it and look at the dimensions of the result?

**Comment by aearamos** [comment]
You're right, the variable is 1D. Here's a ncdump -h of the output:

` ncdump -h out.nc 
netcdf out {
dimensions:
	time = UNLIMITED ; // (1 currently)
	bnds = 2 ;
	rgrid = 88838 ;
variables:
	double time(time) ;
		time:standard_name = "time" ;
		time:bounds = "time_bnds" ;
		time:units = "hours since 1990-1-1 00:00:00" ;
		time:calendar = "proleptic_gregorian" ;
		time:axis = "T" ;
	double time_bnds(time, bnds) ;
	float var129(time, rgrid) ;
		var129:table = 128 ;
		var129:CDI_grid_type = "gaussian_reduced" ;

// global attributes:
		:CDI = "Climate Data Interface version 1.9.3 (http://mpimet.mpg.de/cdi)" ;
		:Conventions = "CF-1.6" ;
		:history = "Thu Sep 06 14:37:09 2018: cdo -f nc -sp2gpl -monmean -selcode,129 129.128.1.6 out.nc" ;
		:institution = "European Centre for Medium-Range Weather Forecasts" ;
		:frequency = "mon" ;
		:CDO = "Climate Data Operators version 1.9.3 (http://mpimet.mpg.de/cdo)" ;
`
So, I've been thinking about my ppt files. I have 129 in my 3D levels (MFP3DFP), in my model levels ( MFP3DFS), and in my 2D variables (MFPPHY). So, in order to have orog, I should have 129 in the ppt0000000000 and pptdddddd0000, right? 

If I run cmorization with 129 only in my ppt0000000000, then I only get 129 in the 5 vertical levels, code 129.128.210.6. But if I have 129 in both files, then I get 129.128.210.6 and 129.128.1.6. I guess the second one should be for orog and that's where I'm getting the wrong dimensions.

**Comment by etiennesky** [comment]
No need for orography at at timesteps, since it does not vary through time.  
You should only have it in the ppt0000000000 .  
If you want it in spectral add it to MFP2DF and if you want it in gridpoint add it to MFPPHY.

Do we really need 129 in model levels, which is not orography but geopotential?

**Comment by goord** [comment]
Some requested variables seem to do so, e.g. zg in CFday I believe.

**Comment by klauswyser** [comment]
I think your problem is probably related to the this bug: https://dev.ec-earth.org/issues/547 The ICMSH*+000000 file contains only the model levels but not pressure levels or surface because the wroutspgb is called twice during the first timestep with file mode is set to "w" which means create a new file. This means your ICMSH file has only geopotential at model levels, and the orography at the surface (par 129) is taken from the ICMGG file. This then means that 
````
cdo -f nc -sp2gpl -monmean -selcode,129 129.128.1.6 out.nc
`````
yields a 1-d array of size 88838x1 because ´´sp2gpl´´  doesn't do anything on gridpoint fields (and it doesn't produce an error) and there is no ´´setgridtype,regular´´. I have suggested a bugfix in https://dev.ec-earth.org/issues/547, if it is accepted the ICMSH*+000000 file will be complete and the post-processing will be just fine.

Alternatively, we may decide to always use orography from the gridpoint file ICMGG*+000000 and change the cdo command in ece2cmor3  accordingly.

**Comment by goord** [comment]
You are correct Klaus, the underlying problem is that the cdo command sp2gpl is added because ece2cmor3 deems 129 to be a 'spectral' grib code which is in this case not true (it can be both, in fact). The solution is that ece2cmor3 should look in the grib file at hand, 129 129.128.1.6, and determine whether this contains spectral or gridpoint data.

This is all due to the fact that in the beginning I wrongly believed variables are either spectral or gridpoint. @aearamos I will have the issue fixed by tomorrow.

**Comment by goord** [comment]
Hi @aearamos can you try to produce orog once more?

**Comment by aearamos** [comment]
Hi, @goord. The cmorization worked for "orog", however, some variables that are later calculated in the ifspar.json file are all missing. Some are "mrso, mrfso, snd, sfcWind, sfcWindmax", "huss" and "rsut". Before I had these variables working just fine. As I understand, they don't produce a "match_key" from grib_flter.py, so it must be after that step.

**Comment by goord** [comment]
Sorry about that, I made the grib message - cmor task matching too strict, I noticed this is a bit of a mess... I have committed some changes, the orog-fix branch is on my system able to process those variables from old primavera output...

**Comment by aearamos** [comment]
Hi, Gijs. You're saying you're able to cmorize the variables that come from ifspar.json? I'm still getting the following for the variables I mentioned before:

`ERROR:ece2cmor3.cmor_source:Unknown grib code 214.128 in expression var214=sqrt(sqr(var165)+sqr(var166)) found
ERROR:ece2cmor3.cmor_source:Unknown grib code 81.128 in expression var81=1./(1.+1.608*(var134*exp(-17.62*(var168-273.15)/(var168-30.03))/611.-1.)) found
`
I don't have these variables in my ppt files, since they're post processed,  but I have them in my ifspar.json for sure. 

Apparently, for me, there is a mismatch in my code and my ifs_source.grib_codes in cmor_source.py. For all the missing variables I get:

 code
43.128 
ERROR:ece2cmor3.cmor_source:Unknown grib code 43.128 in expression var43=70*var39+210*var40+720*var41+1890*var42 found

I understand there were some changes in this part of the code from before, right? 

Thank you for your help.

**Comment by goord** [comment]
Hi @aearamos I figured out that is a different bug, should be resolved in 7bacaec2b43814365da2f163faae7fc3a1441aba. BTW are you using an old ifspar.json file by any chance? It should work with those, I just hadn't tested it thoroughly...

**Comment by aearamos** [comment]
Hi, @goord. I just compared the files and yes, apparently I was using an old version of ifspar.json, so I just updated it and now all the variables work, except for tdps. I still have the same issue as before, in which I have two 168.128 variables ((168, 128, 105, 2, 0) and  (168, 128, 1, 0, 0)). I was able to fix it by changing how some lines in get_levels and in get_record_key, but I'm not sure this is the right path. Maybe I can send you my fix? 

thanks

**Comment by goord** [comment]
Sure you can post it here. I think we should change the get_levels functions in grib_filter.py to return the height_level code and 2 metre in the case of dewpoint temperature in huss

**Comment by goord** [comment]
I committed my fix in the branch and it should work now. If not, I propose you upload a leg to the ecmwf so I can debug ece2cmor3 over there....

**Comment by aearamos** [comment]
It worked, for all the variables. The one variable I have missing is not outputed by IFS (prhmax) and it's in another issue. I'll update it from there. 

Many thanks

**Comment by goord** [comment]
Ok I will merge this branch in the master then

**Comment by aearamos** [comment]
Hi @goord. Today, as I pulled from master to use the last version with all the changes, the error in cmorizing orog for Emon appeared again. Is it possible not all changes have been applied? Can you test the variable in your side?
 Thanks

**Comment by goord** [comment]
Do have the same error as before?

**Comment by aearamos** [comment]
Yes. I have 129 in all 5 vertical levels, but the error I get is

`ERROR:ece2cmor3.grib_filter:Field missing in the first day of file: code 129.128, level type 1, level 0. Dismissing task orog in table Emon`

So, it's the same error as before I think. 

For this run I don't have 129 in my MPPHY list in the pptddd file. I have it on model levels and  pressure levels.

**Comment by goord** [comment]
Ok, so we should also match the 'highest' (?) vertical level of 129 to orog? That's more complicated because ece2cmor3 doesn't know the number of vertical levels...

**Comment by etiennesky** [comment]
To be safe we should have orography at the surface, both in SH and GG files. But probably only the first timestep though, since they don't vary in time (unlike geopotential). Would that be possible from the point of view of cmorization?

**Comment by goord** [comment]
Well the requested variable orog has a time axis, so we would have to copy the initial fields to all the time slices. It is possible, but it does take some work in ece2cmor3.

**Comment by etiennesky** [comment]
Thanks, tt would be wasteful to save things like land-sea mask and orography at every timestep.

**Comment by aearamos** [comment]
I tried what Gijs suggested and added 129 to my MPPHY list for the pptd file as well. Now cmorization works for orog. But with this configuration we'll have orog in every time-step.

**Comment by goord** [comment]
For the implementation, I propose we add a keyword 'constant' or something to the ifspar.json which signals ece2cmor3 that it should copy the initial time slice over and over again. I will create this when I have time (but for the time being you'll be stuck with spurious extra 2D field)

**Comment by goord** [comment]
Hi, it is recommended by ecmwf to always add 129 to the surface fields, which is done by drq2ppt. Hence we can assume in ece2cmor3 that this field is available at all time steps. This may be not efficient for storage, but remember that most experiments will have many, many surface fields...

**Comment by aearamos** [comment]
Hi @goord, looking at the last updates, when trying to cmorize huss and hurs, I noticed that 168.128 wasn't being processed again. I think there's probably a "typo" in line 127 in grib_filter.py:

127    #    if codevar in [167, 168, 201, 202]:
128          if codevar in [167, 201, 202]:

I think the right code is line 127, and not 128, so 168.128 can be processed at different levels.

After changing that line I was able to process huss and hurs and some other variables.

**Comment by goord** [comment]
Hi this was changed when the develop_bsc_cmip6 was merged into the master, I'm not sure why, perhaps a merging thing. @pabretonniere was this change intentional?

**Comment by aearamos** [comment]
This was a first change to try to fix the problem with tdps, but it was a long time ago before we had this discussion. I guess we can use line 127 instead of 128 since the code has changed so much and the problem was fixed. Let's just wait for Pierre-Antoine's confirmation.
