### ISSUE TITLE
macOS conda cdo seems without netcdf4 support

### ISSUE THREAD

**Issue by anthoni-p** [EC-Earth/ece2cmor3#269]
ece2cmor --tmpdir $PWD/tmp --lpj test/test_data/lpjg/001/CMIP6/ 1990-01-01

weird, it seems the conda cdo (at /Users/anthoni-p/software/miniconda3/envs/ece2cmor3/bin/cdo) is without NetCDF4 and fails with:
```
Error in calling operator remapycon with:
>>> cdo -O remapycon,n128 -setgrid,/Users/anthoni-p/EC-Earth/ece2cmor3/ece2cmor3/resources/ingrid_T255_unstructured.txt /Users/anthoni-p/EC-Earth/ece2cmor3/tmp/LPJGtemp.nc /Users/anthoni-p/EC-Earth/ece2cmor3/tmp/intermediate.nc<<<
STDOUT:
STDERR:cdo remapycon: Started child process "setgrid,/Users/anthoni-p/EC-Earth/ece2cmor3/ece2cmor3/resources/ingrid_T255_unstructured.txt /Users/anthoni-p/EC-Earth/ece2cmor3/tmp/LPJGtemp.nc (pipe1.1)".
cdo(2) setgrid: Open failed on >/Users/anthoni-p/EC-Earth/ece2cmor3/tmp/LPJGtemp.nc<
Unsupported file type (library support not compiled in)
To create a CDO application with NetCDF4 support use: ./configure --with-netcdf=<NetCDF4 root directory> ...
```

Workaround, remove conda cdo and symlink to the macOS cdo:
```
mv /Users/anthoni-p/software/miniconda3/envs/ece2cmor3/bin/cdo /Users/anthoni-p/software/miniconda3/envs/ece2cmor3/bin/cdox
cd /Users/anthoni-p/software/miniconda3/envs/ece2cmor3/bin/
ln -s /opt/local/bin/cdo cdo
```
then ece2cmor3 works for me.

**Comment by treerink** [comment]
I think in #268 the trouble was solved right? So closing this issue. Reopen if I am wrong.

**Comment by anthoni-p** [comment]
unfortunately, it still persist. I again had to remove the conda bin/cdo and make a symbolic link to my macOS.

**Comment by treerink** [comment]
The title of this issue suggests that the loaded cdo package is not netcdf4 supporting. However in the `env-osx-64.yml` file we use the
`````
- cdo=1.9.3
`````
package which according to conda cdo has the following dependencies:
`````
depends | eccodes, fftw, jasper, libnetcdf 4.4.*, libxml2 2.9.*, proj4 4.9.3, udunits2
`````

You could try to replace
`````
- cdo=1.9.3
`````
by the newest:
`````
cdo=1.9.5=hecfb957_3
`````
which depends on
`````
cmor, eccodes, fftw, jasper >=1.900.1,<2.0a0, json-c >=0.12.1,<0.13.0a0, libgfortran >=3.0, libnetcdf >=4.6.1,<4.7.0a0, libxml2 >=2.9.8,<2.10.0a0, ossuuid, proj4 >=4.9.3,<4.9.4.0a0, udunits2
`````
which remarkable depends on cmor as well.

**Comment by anthoni-p** [comment]
updated the conda env with the cdo=1.9.5=hecfb957_3, but cdo -V states similar to the cdo v1.9.3 no netCDF support:
```
cdo -V
Climate Data Operators version 1.9.5 (http://mpimet.mpg.de/cdo)
System: x86_64-apple-darwin16.7.0
CXX Compiler: clang++ -std=gnu++11  -mmacosx-version-min=10.9 -stdlib=libc++ -m64 -fPIC  -D_THREAD_SAFE -pthread
CXX version : Apple LLVM version 9.0.0 (clang-900.0.37)
C Compiler: clang  -mmacosx-version-min=10.9 -m64 -fPIC  -D_THREAD_SAFE -pthread -D_THREAD_SAFE -D_THREAD_SAFE -pthread
C version : Apple LLVM version 9.0.0 (clang-900.0.37)
F77 Compiler: gfortran -g -O2
F77 version : GNU Fortran (GCC) 4.8.5
Features: 16GB 4threads C++11 Fortran DATA PTHREADS SSE3
Libraries:
Filetypes: srv ext ieg grb1 
     CDI library version : 1.9.5
 CGRIBEX library version : 1.9.1
    EXSE library version : 1.4.0
    FILE library version : 1.8.3
```
That is quite strange, my own macOS cdo has the following:
```
Climate Data Operators version 1.9.0 (http://mpimet.mpg.de/cdo)
Compiled: by root on IMK-IFU-L3301.local (x86_64-apple-darwin16.7.0) Sep 21 2017 09:49:49
CXX Compiler: /usr/bin/clang++ -std=gnu++11 -pipe -Os -stdlib=libc++ -arch x86_64  -D_THREAD_SAFE -pthread
CXX version : unknown
C Compiler: /usr/bin/clang -pipe -Os -arch x86_64  -D_THREAD_SAFE -pthread
C version : unknown
Features: DATA PTHREADS HDF5 NC4/HDF5 OPeNDAP UDUNITS2 PROJ.4 CURL FFTW3 SSE4_1
Libraries: HDF5/1.10.1 proj/4.93 curl/7.55.1
Filetypes: srv ext ieg grb1 nc1 nc2 nc4 nc4c 
     CDI library version : 1.9.0 of Sep 21 2017 09:49:13
 CGRIBEX library version : 1.8.1 of Jul 12 2017 18:11:37
  NetCDF library version : 4.4.1.1 of Jul 15 2017 09:29:02 $
    HDF5 library version : 1.10.1
 SERVICE library version : 1.4.0 of Sep 21 2017 09:49:08
   EXTRA library version : 1.4.0 of Sep 21 2017 09:49:06
     IEG library version : 1.4.0 of Sep 21 2017 09:49:07
    FILE library version : 1.8.3 of Sep 21 2017 09:49:06
```

**Comment by treerink** [comment]
Hmm strange, it reminds me a bit to a problem I had a year ago with the `gdal` package. It appeared that after just installing that package on linux and on mac there was a different behaviour: on linux netcdf support was included and on mac not. On mac I had to specify some `--with-netcdf` flag. A quick search with keywords "cdo with netcdf mac os" gives for instance [this hit](https://code.mpimet.mpg.de/boards/1/topics/6204):
`````
To create a CDO application with NetCDF support use: ./configure --with-netcdf=<NetCDF root directory>
`````
I don't have a mac anymore myself, so try and test is impossible for me.

**Comment by anthoni-p** [comment]
that is not the problem, my mac cdo has netcdf4 and hdf5 support.
```
cdo -V
...
  NetCDF library version : 4.4.1.1 of Jul 15 2017 09:29:02 $
    HDF5 library version : 1.10.1
```
it is the python cdo that is downloaded from somewhere, that doesn't seem to have it (or maybe it expects to have some netcdf library in a different path and turns of netCDF if it doesn't find it). 
I don't think that I can recompile the python cdo, nevertheless it works for me that I remove the python cdo and make a symbol link to my mac cdo.
