### ISSUE TITLE
Produce fx sftlf based on the the data as published on b2share

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#705]
Produce` fx sftlf` based on the the data as published for each EC-Earth3 resolution in the [ece2cmor3-data set on b2share](https://b2share.eudat.eu/records/f979c6801d434754882cc9172c2305cb).

**Comment by goord** [comment]
This can be tested in branch ``sftlf-b2share``

**Comment by treerink** [comment]
Hi Gijs, thanks. I tried, and got on the KNMI HPC:
```
Traceback (most recent call last):
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 140, in main
    cdothreads=args.ncdo)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 198, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ifs2cmor.py", line 251, in execute
    pool.map(cmor_worker, proctasks)
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /api/records/f7de9a85cbd443269958f0b80e7bc654 (Caused by None)
```

**Comment by treerink** [comment]
On my laptop I have:
```
2021-06-07 12:58:29 INFO:ece2cmor3.ifs2cmor: Executing 1 IFS tasks...
2021-06-07 12:58:29 DEBUG:urllib3.connectionpool: Starting new HTTPS connection (1): b2share.eudat.eu:443
2021-06-07 12:58:29 DEBUG:urllib3.connectionpool: https://b2share.eudat.eu:443 "GET /api/records/f7de9a85cbd443269958f0b80e7bc654 HTTP/1.1" 200 7945
2021-06-07 12:58:29 INFO:ece2cmor3.ifs2cmor: Cmorizing source variable 172 to target variable sftlf...
```
but run into other trouble thereafter. Where should the downloaded file for `fx sftlf` end up actually?

**Comment by goord** [comment]
It should end up in your temp dir as sftlf_fx.nc with the rest of the files

**Comment by goord** [comment]
I had to update the b2share record string in ece2cmor3 because the new files are only in the latest version. I don't understand why on the bull we're seeing connection problems...

**Comment by goord** [comment]
hmm in my browser it also complains it can't connect...

**Comment by treerink** [comment]
I think you branched out from a master which was not the latest master version (but one just before I updated the b2share link for the nemo-vertices). With the consequence I get merge conflicts if I try to merge the master into this branch (for testing I actually need this merge).

Actually I had expect that you would replace for instance
```
 resources/nemo-vertices/ ==> resources/b2share-data
```
And that for the new part there would be a check for instance on:
```
resources/nemo-vertices/fx-sftlf-EC-Earth3-T255.nc
```
and if not present that it would be downloaded in that directory? As we do for the nemo-vertices.

**Comment by goord** [comment]
Aha I see, that makes sense.

I always download the sftlf to the temporary directory, but you're right I could also download it once to the resources like the nemo vertices. That may result in less traffic. Ok I will look at it this evening

**Comment by goord** [comment]
I have implemented the new cache directory in the b2share-sftlf branch

**Comment by treerink** [comment]
After updating & merging the master in the `b2share-sftlf` branch, I still get stuck with the same error on the KNMI HPC with the downloading from b2share:
```
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/bin/ece2cmor", line 11, in <module>
    load_entry_point('ece2cmor3', 'console_scripts', 'ece2cmor')()
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmor.py", line 140, in main
    cdothreads=args.ncdo)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ece2cmorlib.py", line 198, in perform_ifs_tasks
    ifs2cmor.execute(ifs_tasks, nthreads=taskthreads)
  File "/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/ifs2cmor.py", line 251, in execute
    pool.map(cmor_worker, proctasks)
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/lustre2/projects/model_testing/reerink/miniconda2/envs/ece2cmor3/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /api/records/f7de9a85cbd443269958f0b80e7bc654 (Caused by None)
```

Also if I cmorise only the very first leg (so not launching several legs at the same time, that could be problematic, I can imagine, if the jobs at the same time detect the file is absent and they try to write more or less at the same time to the same file).

**Comment by goord** [comment]
Thomas can you check whether you can access the files with e.g. wget on that machine?

**Comment by treerink** [comment]
Yes with `wget` I am able to manually download the following file on the KNMI HPC:
```
 ece2cmor/resources/b2share-data/fx-sftlf-EC-Earth3-T255.nc
```
However, when I try to cmorise `fx` `sftlf` thereafter (with only this variable in the varlist), I still get the same error:
```
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /api/records/f7de9a85cbd443269958f0b80e7bc654 (Caused by None)
```

**Comment by goord** [comment]
hmm, can you put a print statement on line 1010 of ifs2cmor.py? There you can print the fullpath variable and see whether it matches you r downloaded file path?

**Comment by treerink** [comment]
That gives:
```
('THOMAS debug: ', '/nfs/home/users/reerink/cmorize/ece2cmor3/ece2cmor3/resources/b2share-data/fx-sftlf-EC-Earth3-T127.nc')
```
There seems to be a strange  T lable, saw something similar in error on laptop

**Comment by treerink** [comment]
I guess something here:
```
fname = "fx-sftlf-EC-Earth3-T" + str(Nj / 2 - 1) + ".nc"
```

**Comment by goord** [comment]
Yes seems I am calculating the resolution incorrectly...

**Comment by goord** [comment]
It should be just ``Nj - 1``, my bad...

**Comment by goord** [comment]
Pushed a fix to the branch...

**Comment by treerink** [comment]
Thanks, yes now I am able to cmorise on the KNMI HPC. The b2share file has been downloaded in advance.

I will do some more testing later, but this looks fine!

**Comment by treerink** [comment]
Hi Gijs,

I did the `test-all` test as well with this `sftlf-b2share` branch. Actually all seems ok on the IFS and thus `sftlf` side. But I have one unexpected change, and remarkably it is a change in the NEMO error list: These long standing errors are gone, but I guess not for the good reason:

```
 ERROR:ece2cmor3.nemo2cmor: Dimension ncatice could not be found in file /lustre3/projects/CMIP6/reerink/ec-earth-3/branch-r8403-output-control-files/t001/output/nemo/001/t001_1d_19900101_19901231_lim_grid_T_2D.nc, inserting using length-one dimension instead
 ERROR:ece2cmor3.nemo2cmor: Dimension ncatice could not be found in file /lustre3/projects/CMIP6/reerink/ec-earth-3/branch-r8403-output-control-files/t001/output/nemo/001/t001_1m_19900101_19901231_lim_grid_T_2D.nc, inserting using length-one dimension instead
 ERROR:ece2cmor3.nemo2cmor: The grid lim_grid_1point consists of a single point which is not supported, dismissing variables siarean in SImon,sivols in SImon,siareas in SImon,sivoln in SImon,siextents in SImon,siextentn in SImon
 ERROR:ece2cmor3.nemo2cmor: The grid opa_grid_1point consists of a single point which is not supported, dismissing variables thetaoga in Omon,sosga in Omon,zostoga in Omon,volo in Omon,tosga in Omon,bigthetaoga in Omon,masso in Omon,soga in Omon
```

Do you have any idea why this happened? The `test-all` test has been rather stable over a  long time, so there seems to have been really changed something causing this difference?

**Comment by goord** [comment]
I'm sorry @treerink I haven't got any idea, are the variables ``sivoln``, ``siextents``, ``siextentn`` produced? Or no longer requested?

**Comment by treerink** [comment]
No they are not suddenly produced unfortunately, that would have been great :)

No I did not change anything in the request, I assume you also did not changed anything on that part in this branch?

Yes, it is rather puzzling...

**Comment by treerink** [comment]
Ok the problem was that my error checks, checked on "ERROR"  and now we have a severe error which is:
```
DEBUG:urllib3.connectionpool: Starting new HTTPS connection (1): b2share.eudat.eu:443
```
whereafter it quits the entire NEMO cmorisation. That means a lot of NEMO variables are not cmorised, and thus the reported cases were not longer encountered.

I guess this happens when the function `get_from_b2share` in `cmor_utils.py` is called.

**Comment by goord** [comment]
Hi Thomas, you probably need to transfer the NEMO vertex files to the new directory?

**Comment by treerink** [comment]
Yes correct. Once all ece2cmor b2share files are in place, the test-all test is ok now.

I added for all ece2cmor b2share files the manual download instruction in a2376da. But as mentioned in #710 it is convenient to add a simple script for this and to add it to the install instruction.

**Comment by treerink** [comment]
After the sftlf b2share branch merge in #711 and adding the b2share download script in #710 we are done.
