### ISSUE TITLE
AttributeError: module 'cdo' has no attribute 'CDO_PY_VERSION'

### ISSUE THREAD

**Issue by treerink** [EC-Earth/ece2cmor3#770]
Broken over the last weeks (externally). Will try to fix it asap.

The pytest reports the error as:
```
FAILED test/taskloader_test.py::taskloader_test::test_use_zg_preferences - AttributeError: module 'cdo' has no attribute 'CDO_PY_VERSION'
================== 40 failed, 58 passed, 1 warning in 12.84s ===================
Error: Process completed with exit code 1.
```

**Comment by treerink** [comment]
With 5413e5d the _pytests_ are fixed and with that the _ece2cmor3_ package for an install with the most recent `python3.11.4` version. Unfortunately the fix is not backward compatible with `python3.11.0` because an entire list of basic CDO-python attributes has been removed and the version attribute has been replaced. The following has changed:

- The version attribute of CDO_PY has changed between python3.11.0 & python3.11.4, now it can be called by _cdo.\_\_version\_\__
- The CDO_PY version is now at 1.6.0
- The CMOR version is now at 3.7.2
- The CDO version now at 2.2.0
- The python3 version is now at 3.11.4
- The latest current mamba & conda to versions are respectively at 1.4.4 & 23.1.0

Note that due to the upgrade to CMOR 3.7.2 the number of deprecated warnings has been reduced from 9 to 1, because with this CMOR 3.7.2 version their numpy deprecated warnings vanish (see #757).


$\large \textrm{\color{red}Important}$: Upgrading to `python3.11.4` via updating your mamba install is thus $\large \textrm{\color{red}required}$ this time in order to be able to use the latest master checkout of ece2cmor3.

**Comment by plesager** [comment]
There is still an issue with an update of mamba as suggested (ie `mamba update -y --name base mamba`). The $\large \textrm{\color{red}Important}$ comment above is misleading or incomplete. I have updated mamba yesterday and here are the versions I got:
```
> mamba update -y --name base mamba
> mamba --version
mamba 1.5.3
conda 23.10.0
> conda activate ece2cmor3
> python -V
Python 3.11.0
```
As you see, the newer mamba (1.5.3 instead of 1.4.4 reported above) does not update python 3.11.0 (instead of 3.11.4) or cdo (2.1.1 instead of 2.2.0). And my CDO_PY_VERSION is 1.5.7.... Users must update their ece2cmor3 env too by removing it and reinstalling it: only that step will update the python (and its packages) version.
